apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
  namespace: default
data:
  fluent-bit.conf: |
    
    [SERVICE]
      Flush             1
      Log_Level         info
      Parsers_File      parsers.conf

    [INPUT]
      Name              tail
      Path              /var/log/app/timestamp.log
      Parser            json
      Tag               app.logs
      Mem_Buf_Limit     2MB
      Skip_Long_Lines   On
      DB                /var/log/flb_tailed.db
      Refresh_Interval  10

    [OUTPUT]
      Name              http
      Match             app.logs
      host              test-auditlogs-endpoint.tiket.tools
      uri               /
      port              9002
      tls               off
      format            json_stream
      Retry_Limit       3
      json_date_key     false
      header            x-vertical platform
      header            x-team message
      header            x-service-name tix-message-batch-be

  parsers.conf: |
    
    [PARSER]
      Name              json
      Format            json
      